adapter_name_or_path: saves/LLaMA3-8B-Chat/lora/5e5_3ep
cutoff_len: 1024
dataset: sms_test
dataset_dir: /root/LLaMA-Factory/data
do_predict: true
finetuning_type: lora
flash_attn: auto
max_new_tokens: 1
max_samples: 100000
model_name_or_path: /root/autodl-tmp/Llama3-8b/LLM-Research/Meta-Llama-3-8B-Instruct
output_dir: saves/LLaMA3-8B-Chat/lora/eval_5e5_sms
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
stage: sft
temperature: 0.95
template: llama3
top_p: 0.7
